%%%
% Author: Humayun Irshad
% Beck lab, BIDMC, Harvard Medical School.
% 2014_05_20
%%%

function [ Features ] = DataStructureDefinition( )
%DataStructureDefinition defines the data structure for nuclei features
%   Defines data structure for nuclei features

    Features = struct('Area',0,'Perimeter',0,'MajorAxisLength',0,...%Morph(11)
      'MinorAxisLength',0,'Eccentricity',0,'ConvexArea',0,'Orientation',0,...
      'EquivDiameter',0,'Solidity',0,'Extent',0,'Compactness',0, ... 
      'Mean_R',0,'Median_R',0,'MAD_R',0,'SD_R',0,'IQR_R',0, ... %Intensity(63)
      'Skewness_R',0,'Kurtosis_R',0, ...
      'Mean_G',0,'Median_G',0,'MAD_G',0,'SD_G',0,'IQR_G',0, ...
      'Skewness_G',0,'Kurtosis_G',0, ...
      'Mean_B',0,'Median_B',0,'MAD_B',0,'SD_B',0,'IQR_B',0, ...
      'Skewness_B',0,'Kurtosis_B',0, ...
      'Mean_V',0,'Median_V',0,'MAD_V',0,'SD_V',0,'IQR_V',0, ...
      'Skewness_V',0,'Kurtosis_V',0, ...
      'Mean_L',0,'Median_L',0,'MAD_L',0,'SD_L',0,'IQR_L',0, ...
      'Skewness_L',0,'Kurtosis_L',0, ...
      'Mean_H',0,'Median_H',0,'MAD_H',0,'SD_H',0,'IQR_H',0, ...
      'Skewness_H',0,'Kurtosis_H',0, ...
      'Mean_Br',0,'Median_Br',0,'MAD_Br',0,'SD_Br',0,'IQR_Br',0, ...
      'Skewness_Br',0,'Kurtosis_Br',0, ...
      'Autocorrelation_R',0,'CorrelationP_R',0,'Contrast_R',0, ... %CM(98)
      'ClusterShade_R',0,'ClusterProminence_R',0,'Energy_R',0, ...
      'Entropy_R',0,'HomogeneityP_R',0,'InverseDiffNormalized_R',0, ...
      'InverseDiffMomentNormalized_R',0,'Dissimilarity_R',0, ...
      'MaxProbability_R',0,'InfoMeasureCorr1_R',0, ... 
      'InformeasureCorr2_R',0, ...
      'Autocorrelation_G',0,'CorrelationP_G',0,'Contrast_G',0, ...
      'ClusterShade_G',0,'ClusterProminence_G',0,'Energy_G',0, ...
      'Entropy_G',0,'HomogeneityP_G',0,'InverseDiffNormalized_G',0, ...
      'InverseDiffMomentNormalized_G',0,'Dissimilarity_G',0, ...
      'MaxProbability_G',0,'InfoMeasureCorr1_G',0, ... 
      'InformeasureCorr2_G',0, ...
      'Autocorrelation_B',0,'CorrelationP_B',0,'Contrast_B',0, ...
      'ClusterShade_B',0,'ClusterProminence_B',0,'Energy_B',0, ...
      'Entropy_B',0,'HomogeneityP_B',0,'InverseDiffNormalized_B',0, ...
      'InverseDiffMomentNormalized_B',0,'Dissimilarity_B',0, ...
      'MaxProbability_B',0,'InfoMeasureCorr1_B',0, ... 
      'InformeasureCorr2_B',0, ...
      'Autocorrelation_V',0,'CorrelationP_V',0,'Contrast_V',0, ...
      'ClusterShade_V',0,'ClusterProminence_V',0,'Energy_V',0, ...
      'Entropy_V',0,'HomogeneityP_V',0,'InverseDiffNormalized_V',0, ...
      'InverseDiffMomentNormalized_V',0,'Dissimilarity_V',0, ...
      'MaxProbability_V',0,'InfoMeasureCorr1_V',0, ... 
      'InformeasureCorr2_V',0, ...
      'Autocorrelation_L',0,'CorrelationP_L',0,'Contrast_L',0, ...
      'ClusterShade_L',0,'ClusterProminence_L',0,'Energy_L',0, ...
      'Entropy_L',0,'HomogeneityP_L',0,'InverseDiffNormalized_L',0, ...
      'InverseDiffMomentNormalized_L',0,'Dissimilarity_L',0, ...
      'MaxProbability_L',0,'InfoMeasureCorr1_L',0, ... 
      'InformeasureCorr2_L',0, ...
      'Autocorrelation_H',0,'CorrelationP_H',0,'Contrast_H',0, ...
      'ClusterShade_H',0,'ClusterProminence_H',0,'Energy_H',0, ...
      'Entropy_H',0,'HomogeneityP_H',0,'InverseDiffNormalized_H',0, ...
      'InverseDiffMomentNormalized_H',0,'Dissimilarity_H',0, ...
      'MaxProbability_H',0,'InfoMeasureCorr1_H',0, ... 
      'InformeasureCorr2_H',0, ...
      'Autocorrelation_Br',0,'CorrelationP_Br',0,'Contrast_Br',0, ...
      'ClusterShade_Br',0,'ClusterProminence_Br',0,'Energy_Br',0, ...
      'Entropy_Br',0,'HomogeneityP_Br',0,'InverseDiffNormalized_Br',0, ...
      'InverseDiffMomentNormalized_Br',0,'Dissimilarity_Br',0, ...
      'MaxProbability_Br',0,'InfoMeasureCorr1_Br',0, ... 
      'InformeasureCorr2_Br',0, ...
      'SRE_R',0, 'LRE_R',0, 'GLN_R',0, 'RLN_R',0, 'RP_R',0, 'LGRE_R',0,...%RL(77)
      'HGRE_R',0, 'SRLGE_R',0, 'SRHGE_R',0, 'LRLGE_R',0, 'LRHGE_R',0, ...
      'SRE_G',0, 'LRE_G',0, 'GLN_G',0, 'RLN_G',0, 'RP_G',0, 'LGRE_G',0, ...
      'HGRE_G',0, 'SRLGE_G',0, 'SRHGE_G',0, 'LRLGE_G',0, 'LRHGE_G',0, ...
      'SRE_B',0, 'LRE_B',0, 'GLN_B',0, 'RLN_B',0, 'RP_B',0, 'LGRE_B',0, ...
      'HGRE_B',0, 'SRLGE_B',0, 'SRHGE_B',0, 'LRLGE_B',0, 'LRHGE_B',0, ...
      'SRE_V',0, 'LRE_V',0, 'GLN_V',0, 'RLN_V',0, 'RP_V',0, 'LGRE_V',0, ...
      'HGRE_V',0, 'SRLGE_V',0, 'SRHGE_V',0, 'LRLGE_V',0, 'LRHGE_V',0, ...
      'SRE_L',0, 'LRE_L',0, 'GLN_L',0, 'RLN_L',0, 'RP_L',0, 'LGRE_L',0, ...
      'HGRE_L',0, 'SRLGE_L',0, 'SRHGE_L',0, 'LRLGE_L',0, 'LRHGE_L',0, ...
      'SRE_H',0, 'LRE_H',0, 'GLN_H',0, 'RLN_H',0, 'RP_H',0, 'LGRE_H',0, ...
      'HGRE_H',0, 'SRLGE_H',0, 'SRHGE_H',0, 'LRLGE_H',0, 'LRHGE_H',0, ...
      'SRE_Br',0,'LRE_Br',0,'GLN_Br',0,'RLN_Br',0,'RP_Br',0,'LGRE_Br',0,...
      'HGRE_Br',0, 'SRLGE_Br',0, 'SRHGE_Br',0, 'LRLGE_Br',0, 'LRHGE_Br',0);
end

